//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace books_and_genres_with_entity_framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int NumOfPages { get; set; }
        public string MainAuthor { get; set; }
        public int IdGenres { get; set; }
    
        public virtual Genres Genres { get; set; }
    }
}
